"""Telegram API 定义。"""
# autogenerated by codegen.py, do not edit manually.
# ruff: noqa: D101, D102, A002

from typing import Optional, Union

from .model import (
    BotCommand,
    BotCommandScope,
    BotDescription,
    BotName,
    BotShortDescription,
    BusinessConnection,
    ChatAdministratorRights,
    ChatFullInfo,
    ChatInviteLink,
    ChatMember,
    ChatPermissions,
    File,
    ForceReply,
    ForumTopic,
    GameHighScore,
    InlineKeyboardMarkup,
    InlineQueryResult,
    InlineQueryResultsButton,
    InputFile,
    InputMedia,
    InputMediaAudio,
    InputMediaDocument,
    InputMediaPhoto,
    InputMediaVideo,
    InputPaidMedia,
    InputPollOption,
    InputSticker,
    LabeledPrice,
    LinkPreviewOptions,
    MaskPosition,
    MenuButton,
    Message,
    MessageEntity,
    MessageId,
    PassportElementError,
    Poll,
    ReactionType,
    ReplyKeyboardMarkup,
    ReplyKeyboardRemove,
    ReplyParameters,
    SentWebAppMessage,
    ShippingOption,
    StarTransactions,
    Sticker,
    StickerSet,
    Update,
    User,
    UserChatBoosts,
    UserProfilePhotos,
    WebhookInfo,
)


class TelegramAPI:
    async def get_updates(
        self,
        *,
        offset: Optional[int] = None,
        limit: Optional[int] = None,
        timeout: Optional[int] = None,
        allowed_updates: Optional[list[str]] = None,
    ) -> list[Update]: ...

    async def set_webhook(
        self,
        *,
        url: str,
        certificate: Optional[InputFile] = None,
        ip_address: Optional[str] = None,
        max_connections: Optional[int] = None,
        allowed_updates: Optional[list[str]] = None,
        drop_pending_updates: Optional[bool] = None,
        secret_token: Optional[str] = None,
    ) -> bool: ...

    async def delete_webhook(
        self,
        *,
        drop_pending_updates: Optional[bool] = None,
    ) -> bool: ...

    async def get_webhook_info(
        self,
    ) -> WebhookInfo: ...

    async def get_me(
        self,
    ) -> User: ...

    async def log_out(
        self,
    ) -> bool: ...

    async def close(
        self,
    ) -> bool: ...

    async def send_message(
        self,
        *,
        chat_id: Union[int, str],
        text: str,
        business_connection_id: Optional[str] = None,
        message_thread_id: Optional[int] = None,
        parse_mode: Optional[str] = None,
        entities: Optional[list[MessageEntity]] = None,
        link_preview_options: Optional[LinkPreviewOptions] = None,
        disable_notification: Optional[bool] = None,
        protect_content: Optional[bool] = None,
        message_effect_id: Optional[str] = None,
        reply_parameters: Optional[ReplyParameters] = None,
        reply_markup: Optional[
            Union[
                InlineKeyboardMarkup,
                ReplyKeyboardMarkup,
                ReplyKeyboardRemove,
                ForceReply,
            ]
        ] = None,
    ) -> Message: ...

    async def forward_message(
        self,
        *,
        chat_id: Union[int, str],
        from_chat_id: Union[int, str],
        message_id: int,
        message_thread_id: Optional[int] = None,
        disable_notification: Optional[bool] = None,
        protect_content: Optional[bool] = None,
    ) -> Message: ...

    async def forward_messages(
        self,
        *,
        chat_id: Union[int, str],
        from_chat_id: Union[int, str],
        message_ids: list[int],
        message_thread_id: Optional[int] = None,
        disable_notification: Optional[bool] = None,
        protect_content: Optional[bool] = None,
    ) -> list[MessageId]: ...

    async def copy_message(
        self,
        *,
        chat_id: Union[int, str],
        from_chat_id: Union[int, str],
        message_id: int,
        message_thread_id: Optional[int] = None,
        caption: Optional[str] = None,
        parse_mode: Optional[str] = None,
        caption_entities: Optional[list[MessageEntity]] = None,
        show_caption_above_media: Optional[bool] = None,
        disable_notification: Optional[bool] = None,
        protect_content: Optional[bool] = None,
        reply_parameters: Optional[ReplyParameters] = None,
        reply_markup: Optional[
            Union[
                InlineKeyboardMarkup,
                ReplyKeyboardMarkup,
                ReplyKeyboardRemove,
                ForceReply,
            ]
        ] = None,
    ) -> MessageId: ...

    async def copy_messages(
        self,
        *,
        chat_id: Union[int, str],
        from_chat_id: Union[int, str],
        message_ids: list[int],
        message_thread_id: Optional[int] = None,
        disable_notification: Optional[bool] = None,
        protect_content: Optional[bool] = None,
        remove_caption: Optional[bool] = None,
    ) -> list[MessageId]: ...

    async def send_photo(
        self,
        *,
        chat_id: Union[int, str],
        photo: Union[InputFile, str],
        business_connection_id: Optional[str] = None,
        message_thread_id: Optional[int] = None,
        caption: Optional[str] = None,
        parse_mode: Optional[str] = None,
        caption_entities: Optional[list[MessageEntity]] = None,
        show_caption_above_media: Optional[bool] = None,
        has_spoiler: Optional[bool] = None,
        disable_notification: Optional[bool] = None,
        protect_content: Optional[bool] = None,
        message_effect_id: Optional[str] = None,
        reply_parameters: Optional[ReplyParameters] = None,
        reply_markup: Optional[
            Union[
                InlineKeyboardMarkup,
                ReplyKeyboardMarkup,
                ReplyKeyboardRemove,
                ForceReply,
            ]
        ] = None,
    ) -> Message: ...

    async def send_audio(
        self,
        *,
        chat_id: Union[int, str],
        audio: Union[InputFile, str],
        business_connection_id: Optional[str] = None,
        message_thread_id: Optional[int] = None,
        caption: Optional[str] = None,
        parse_mode: Optional[str] = None,
        caption_entities: Optional[list[MessageEntity]] = None,
        duration: Optional[int] = None,
        performer: Optional[str] = None,
        title: Optional[str] = None,
        thumbnail: Optional[Union[InputFile, str]] = None,
        disable_notification: Optional[bool] = None,
        protect_content: Optional[bool] = None,
        message_effect_id: Optional[str] = None,
        reply_parameters: Optional[ReplyParameters] = None,
        reply_markup: Optional[
            Union[
                InlineKeyboardMarkup,
                ReplyKeyboardMarkup,
                ReplyKeyboardRemove,
                ForceReply,
            ]
        ] = None,
    ) -> Message: ...

    async def send_document(
        self,
        *,
        chat_id: Union[int, str],
        document: Union[InputFile, str],
        business_connection_id: Optional[str] = None,
        message_thread_id: Optional[int] = None,
        thumbnail: Optional[Union[InputFile, str]] = None,
        caption: Optional[str] = None,
        parse_mode: Optional[str] = None,
        caption_entities: Optional[list[MessageEntity]] = None,
        disable_content_type_detection: Optional[bool] = None,
        disable_notification: Optional[bool] = None,
        protect_content: Optional[bool] = None,
        message_effect_id: Optional[str] = None,
        reply_parameters: Optional[ReplyParameters] = None,
        reply_markup: Optional[
            Union[
                InlineKeyboardMarkup,
                ReplyKeyboardMarkup,
                ReplyKeyboardRemove,
                ForceReply,
            ]
        ] = None,
    ) -> Message: ...

    async def send_video(
        self,
        *,
        chat_id: Union[int, str],
        video: Union[InputFile, str],
        business_connection_id: Optional[str] = None,
        message_thread_id: Optional[int] = None,
        duration: Optional[int] = None,
        width: Optional[int] = None,
        height: Optional[int] = None,
        thumbnail: Optional[Union[InputFile, str]] = None,
        caption: Optional[str] = None,
        parse_mode: Optional[str] = None,
        caption_entities: Optional[list[MessageEntity]] = None,
        show_caption_above_media: Optional[bool] = None,
        has_spoiler: Optional[bool] = None,
        supports_streaming: Optional[bool] = None,
        disable_notification: Optional[bool] = None,
        protect_content: Optional[bool] = None,
        message_effect_id: Optional[str] = None,
        reply_parameters: Optional[ReplyParameters] = None,
        reply_markup: Optional[
            Union[
                InlineKeyboardMarkup,
                ReplyKeyboardMarkup,
                ReplyKeyboardRemove,
                ForceReply,
            ]
        ] = None,
    ) -> Message: ...

    async def send_animation(
        self,
        *,
        chat_id: Union[int, str],
        animation: Union[InputFile, str],
        business_connection_id: Optional[str] = None,
        message_thread_id: Optional[int] = None,
        duration: Optional[int] = None,
        width: Optional[int] = None,
        height: Optional[int] = None,
        thumbnail: Optional[Union[InputFile, str]] = None,
        caption: Optional[str] = None,
        parse_mode: Optional[str] = None,
        caption_entities: Optional[list[MessageEntity]] = None,
        show_caption_above_media: Optional[bool] = None,
        has_spoiler: Optional[bool] = None,
        disable_notification: Optional[bool] = None,
        protect_content: Optional[bool] = None,
        message_effect_id: Optional[str] = None,
        reply_parameters: Optional[ReplyParameters] = None,
        reply_markup: Optional[
            Union[
                InlineKeyboardMarkup,
                ReplyKeyboardMarkup,
                ReplyKeyboardRemove,
                ForceReply,
            ]
        ] = None,
    ) -> Message: ...

    async def send_voice(
        self,
        *,
        chat_id: Union[int, str],
        voice: Union[InputFile, str],
        business_connection_id: Optional[str] = None,
        message_thread_id: Optional[int] = None,
        caption: Optional[str] = None,
        parse_mode: Optional[str] = None,
        caption_entities: Optional[list[MessageEntity]] = None,
        duration: Optional[int] = None,
        disable_notification: Optional[bool] = None,
        protect_content: Optional[bool] = None,
        message_effect_id: Optional[str] = None,
        reply_parameters: Optional[ReplyParameters] = None,
        reply_markup: Optional[
            Union[
                InlineKeyboardMarkup,
                ReplyKeyboardMarkup,
                ReplyKeyboardRemove,
                ForceReply,
            ]
        ] = None,
    ) -> Message: ...

    async def send_video_note(
        self,
        *,
        chat_id: Union[int, str],
        video_note: Union[InputFile, str],
        business_connection_id: Optional[str] = None,
        message_thread_id: Optional[int] = None,
        duration: Optional[int] = None,
        length: Optional[int] = None,
        thumbnail: Optional[Union[InputFile, str]] = None,
        disable_notification: Optional[bool] = None,
        protect_content: Optional[bool] = None,
        message_effect_id: Optional[str] = None,
        reply_parameters: Optional[ReplyParameters] = None,
        reply_markup: Optional[
            Union[
                InlineKeyboardMarkup,
                ReplyKeyboardMarkup,
                ReplyKeyboardRemove,
                ForceReply,
            ]
        ] = None,
    ) -> Message: ...

    async def send_paid_media(
        self,
        *,
        chat_id: Union[int, str],
        star_count: int,
        media: list[InputPaidMedia],
        business_connection_id: Optional[str] = None,
        payload: Optional[str] = None,
        caption: Optional[str] = None,
        parse_mode: Optional[str] = None,
        caption_entities: Optional[list[MessageEntity]] = None,
        show_caption_above_media: Optional[bool] = None,
        disable_notification: Optional[bool] = None,
        protect_content: Optional[bool] = None,
        reply_parameters: Optional[ReplyParameters] = None,
        reply_markup: Optional[
            Union[
                InlineKeyboardMarkup,
                ReplyKeyboardMarkup,
                ReplyKeyboardRemove,
                ForceReply,
            ]
        ] = None,
    ) -> Message: ...

    async def send_media_group(
        self,
        *,
        chat_id: Union[int, str],
        media: Union[
            list[InputMediaAudio],
            list[InputMediaDocument],
            list[InputMediaPhoto],
            list[InputMediaVideo],
        ],
        business_connection_id: Optional[str] = None,
        message_thread_id: Optional[int] = None,
        disable_notification: Optional[bool] = None,
        protect_content: Optional[bool] = None,
        message_effect_id: Optional[str] = None,
        reply_parameters: Optional[ReplyParameters] = None,
    ) -> list[Message]: ...

    async def send_location(
        self,
        *,
        chat_id: Union[int, str],
        latitude: float,
        longitude: float,
        business_connection_id: Optional[str] = None,
        message_thread_id: Optional[int] = None,
        horizontal_accuracy: Optional[float] = None,
        live_period: Optional[int] = None,
        heading: Optional[int] = None,
        proximity_alert_radius: Optional[int] = None,
        disable_notification: Optional[bool] = None,
        protect_content: Optional[bool] = None,
        message_effect_id: Optional[str] = None,
        reply_parameters: Optional[ReplyParameters] = None,
        reply_markup: Optional[
            Union[
                InlineKeyboardMarkup,
                ReplyKeyboardMarkup,
                ReplyKeyboardRemove,
                ForceReply,
            ]
        ] = None,
    ) -> Message: ...

    async def send_venue(
        self,
        *,
        chat_id: Union[int, str],
        latitude: float,
        longitude: float,
        title: str,
        address: str,
        business_connection_id: Optional[str] = None,
        message_thread_id: Optional[int] = None,
        foursquare_id: Optional[str] = None,
        foursquare_type: Optional[str] = None,
        google_place_id: Optional[str] = None,
        google_place_type: Optional[str] = None,
        disable_notification: Optional[bool] = None,
        protect_content: Optional[bool] = None,
        message_effect_id: Optional[str] = None,
        reply_parameters: Optional[ReplyParameters] = None,
        reply_markup: Optional[
            Union[
                InlineKeyboardMarkup,
                ReplyKeyboardMarkup,
                ReplyKeyboardRemove,
                ForceReply,
            ]
        ] = None,
    ) -> Message: ...

    async def send_contact(
        self,
        *,
        chat_id: Union[int, str],
        phone_number: str,
        first_name: str,
        business_connection_id: Optional[str] = None,
        message_thread_id: Optional[int] = None,
        last_name: Optional[str] = None,
        vcard: Optional[str] = None,
        disable_notification: Optional[bool] = None,
        protect_content: Optional[bool] = None,
        message_effect_id: Optional[str] = None,
        reply_parameters: Optional[ReplyParameters] = None,
        reply_markup: Optional[
            Union[
                InlineKeyboardMarkup,
                ReplyKeyboardMarkup,
                ReplyKeyboardRemove,
                ForceReply,
            ]
        ] = None,
    ) -> Message: ...

    async def send_poll(
        self,
        *,
        chat_id: Union[int, str],
        question: str,
        options: list[InputPollOption],
        business_connection_id: Optional[str] = None,
        message_thread_id: Optional[int] = None,
        question_parse_mode: Optional[str] = None,
        question_entities: Optional[list[MessageEntity]] = None,
        is_anonymous: Optional[bool] = None,
        type: Optional[str] = None,
        allows_multiple_answers: Optional[bool] = None,
        correct_option_id: Optional[int] = None,
        explanation: Optional[str] = None,
        explanation_parse_mode: Optional[str] = None,
        explanation_entities: Optional[list[MessageEntity]] = None,
        open_period: Optional[int] = None,
        close_date: Optional[int] = None,
        is_closed: Optional[bool] = None,
        disable_notification: Optional[bool] = None,
        protect_content: Optional[bool] = None,
        message_effect_id: Optional[str] = None,
        reply_parameters: Optional[ReplyParameters] = None,
        reply_markup: Optional[
            Union[
                InlineKeyboardMarkup,
                ReplyKeyboardMarkup,
                ReplyKeyboardRemove,
                ForceReply,
            ]
        ] = None,
    ) -> Message: ...

    async def send_dice(
        self,
        *,
        chat_id: Union[int, str],
        business_connection_id: Optional[str] = None,
        message_thread_id: Optional[int] = None,
        emoji: Optional[str] = None,
        disable_notification: Optional[bool] = None,
        protect_content: Optional[bool] = None,
        message_effect_id: Optional[str] = None,
        reply_parameters: Optional[ReplyParameters] = None,
        reply_markup: Optional[
            Union[
                InlineKeyboardMarkup,
                ReplyKeyboardMarkup,
                ReplyKeyboardRemove,
                ForceReply,
            ]
        ] = None,
    ) -> Message: ...

    async def send_chat_action(
        self,
        *,
        chat_id: Union[int, str],
        action: str,
        business_connection_id: Optional[str] = None,
        message_thread_id: Optional[int] = None,
    ) -> bool: ...

    async def set_message_reaction(
        self,
        *,
        chat_id: Union[int, str],
        message_id: int,
        reaction: Optional[list[ReactionType]] = None,
        is_big: Optional[bool] = None,
    ) -> bool: ...

    async def get_user_profile_photos(
        self,
        *,
        user_id: int,
        offset: Optional[int] = None,
        limit: Optional[int] = None,
    ) -> UserProfilePhotos: ...

    async def get_file(
        self,
        *,
        file_id: str,
    ) -> File: ...

    async def ban_chat_member(
        self,
        *,
        chat_id: Union[int, str],
        user_id: int,
        until_date: Optional[int] = None,
        revoke_messages: Optional[bool] = None,
    ) -> bool: ...

    async def unban_chat_member(
        self,
        *,
        chat_id: Union[int, str],
        user_id: int,
        only_if_banned: Optional[bool] = None,
    ) -> bool: ...

    async def restrict_chat_member(
        self,
        *,
        chat_id: Union[int, str],
        user_id: int,
        permissions: ChatPermissions,
        use_independent_chat_permissions: Optional[bool] = None,
        until_date: Optional[int] = None,
    ) -> bool: ...

    async def promote_chat_member(
        self,
        *,
        chat_id: Union[int, str],
        user_id: int,
        is_anonymous: Optional[bool] = None,
        can_manage_chat: Optional[bool] = None,
        can_delete_messages: Optional[bool] = None,
        can_manage_video_chats: Optional[bool] = None,
        can_restrict_members: Optional[bool] = None,
        can_promote_members: Optional[bool] = None,
        can_change_info: Optional[bool] = None,
        can_invite_users: Optional[bool] = None,
        can_post_stories: Optional[bool] = None,
        can_edit_stories: Optional[bool] = None,
        can_delete_stories: Optional[bool] = None,
        can_post_messages: Optional[bool] = None,
        can_edit_messages: Optional[bool] = None,
        can_pin_messages: Optional[bool] = None,
        can_manage_topics: Optional[bool] = None,
    ) -> bool: ...

    async def set_chat_administrator_custom_title(
        self,
        *,
        chat_id: Union[int, str],
        user_id: int,
        custom_title: str,
    ) -> bool: ...

    async def ban_chat_sender_chat(
        self,
        *,
        chat_id: Union[int, str],
        sender_chat_id: int,
    ) -> bool: ...

    async def unban_chat_sender_chat(
        self,
        *,
        chat_id: Union[int, str],
        sender_chat_id: int,
    ) -> bool: ...

    async def set_chat_permissions(
        self,
        *,
        chat_id: Union[int, str],
        permissions: ChatPermissions,
        use_independent_chat_permissions: Optional[bool] = None,
    ) -> bool: ...

    async def export_chat_invite_link(
        self,
        *,
        chat_id: Union[int, str],
    ) -> str: ...

    async def create_chat_invite_link(
        self,
        *,
        chat_id: Union[int, str],
        name: Optional[str] = None,
        expire_date: Optional[int] = None,
        member_limit: Optional[int] = None,
        creates_join_request: Optional[bool] = None,
    ) -> ChatInviteLink: ...

    async def edit_chat_invite_link(
        self,
        *,
        chat_id: Union[int, str],
        invite_link: str,
        name: Optional[str] = None,
        expire_date: Optional[int] = None,
        member_limit: Optional[int] = None,
        creates_join_request: Optional[bool] = None,
    ) -> ChatInviteLink: ...

    async def create_chat_subscription_invite_link(
        self,
        *,
        chat_id: Union[int, str],
        subscription_period: int,
        subscription_price: int,
        name: Optional[str] = None,
    ) -> ChatInviteLink: ...

    async def edit_chat_subscription_invite_link(
        self,
        *,
        chat_id: Union[int, str],
        invite_link: str,
        name: Optional[str] = None,
    ) -> ChatInviteLink: ...

    async def revoke_chat_invite_link(
        self,
        *,
        chat_id: Union[int, str],
        invite_link: str,
    ) -> ChatInviteLink: ...

    async def approve_chat_join_request(
        self,
        *,
        chat_id: Union[int, str],
        user_id: int,
    ) -> bool: ...

    async def decline_chat_join_request(
        self,
        *,
        chat_id: Union[int, str],
        user_id: int,
    ) -> bool: ...

    async def set_chat_photo(
        self,
        *,
        chat_id: Union[int, str],
        photo: InputFile,
    ) -> bool: ...

    async def delete_chat_photo(
        self,
        *,
        chat_id: Union[int, str],
    ) -> bool: ...

    async def set_chat_title(
        self,
        *,
        chat_id: Union[int, str],
        title: str,
    ) -> bool: ...

    async def set_chat_description(
        self,
        *,
        chat_id: Union[int, str],
        description: Optional[str] = None,
    ) -> bool: ...

    async def pin_chat_message(
        self,
        *,
        chat_id: Union[int, str],
        message_id: int,
        business_connection_id: Optional[str] = None,
        disable_notification: Optional[bool] = None,
    ) -> bool: ...

    async def unpin_chat_message(
        self,
        *,
        chat_id: Union[int, str],
        business_connection_id: Optional[str] = None,
        message_id: Optional[int] = None,
    ) -> bool: ...

    async def unpin_all_chat_messages(
        self,
        *,
        chat_id: Union[int, str],
    ) -> bool: ...

    async def leave_chat(
        self,
        *,
        chat_id: Union[int, str],
    ) -> bool: ...

    async def get_chat(
        self,
        *,
        chat_id: Union[int, str],
    ) -> ChatFullInfo: ...

    async def get_chat_administrators(
        self,
        *,
        chat_id: Union[int, str],
    ) -> list[ChatMember]: ...

    async def get_chat_member_count(
        self,
        *,
        chat_id: Union[int, str],
    ) -> int: ...

    async def get_chat_member(
        self,
        *,
        chat_id: Union[int, str],
        user_id: int,
    ) -> ChatMember: ...

    async def set_chat_sticker_set(
        self,
        *,
        chat_id: Union[int, str],
        sticker_set_name: str,
    ) -> bool: ...

    async def delete_chat_sticker_set(
        self,
        *,
        chat_id: Union[int, str],
    ) -> bool: ...

    async def get_forum_topic_icon_stickers(
        self,
    ) -> list[Sticker]: ...

    async def create_forum_topic(
        self,
        *,
        chat_id: Union[int, str],
        name: str,
        icon_color: Optional[int] = None,
        icon_custom_emoji_id: Optional[str] = None,
    ) -> ForumTopic: ...

    async def edit_forum_topic(
        self,
        *,
        chat_id: Union[int, str],
        message_thread_id: int,
        name: Optional[str] = None,
        icon_custom_emoji_id: Optional[str] = None,
    ) -> bool: ...

    async def close_forum_topic(
        self,
        *,
        chat_id: Union[int, str],
        message_thread_id: int,
    ) -> bool: ...

    async def reopen_forum_topic(
        self,
        *,
        chat_id: Union[int, str],
        message_thread_id: int,
    ) -> bool: ...

    async def delete_forum_topic(
        self,
        *,
        chat_id: Union[int, str],
        message_thread_id: int,
    ) -> bool: ...

    async def unpin_all_forum_topic_messages(
        self,
        *,
        chat_id: Union[int, str],
        message_thread_id: int,
    ) -> bool: ...

    async def edit_general_forum_topic(
        self,
        *,
        chat_id: Union[int, str],
        name: str,
    ) -> bool: ...

    async def close_general_forum_topic(
        self,
        *,
        chat_id: Union[int, str],
    ) -> bool: ...

    async def reopen_general_forum_topic(
        self,
        *,
        chat_id: Union[int, str],
    ) -> bool: ...

    async def hide_general_forum_topic(
        self,
        *,
        chat_id: Union[int, str],
    ) -> bool: ...

    async def unhide_general_forum_topic(
        self,
        *,
        chat_id: Union[int, str],
    ) -> bool: ...

    async def unpin_all_general_forum_topic_messages(
        self,
        *,
        chat_id: Union[int, str],
    ) -> bool: ...

    async def answer_callback_query(
        self,
        *,
        callback_query_id: str,
        text: Optional[str] = None,
        show_alert: Optional[bool] = None,
        url: Optional[str] = None,
        cache_time: Optional[int] = None,
    ) -> bool: ...

    async def get_user_chat_boosts(
        self,
        *,
        chat_id: Union[int, str],
        user_id: int,
    ) -> UserChatBoosts: ...

    async def get_business_connection(
        self,
        *,
        business_connection_id: str,
    ) -> BusinessConnection: ...

    async def set_my_commands(
        self,
        *,
        commands: list[BotCommand],
        scope: Optional[BotCommandScope] = None,
        language_code: Optional[str] = None,
    ) -> bool: ...

    async def delete_my_commands(
        self,
        *,
        scope: Optional[BotCommandScope] = None,
        language_code: Optional[str] = None,
    ) -> bool: ...

    async def get_my_commands(
        self,
        *,
        scope: Optional[BotCommandScope] = None,
        language_code: Optional[str] = None,
    ) -> list[BotCommand]: ...

    async def set_my_name(
        self,
        *,
        name: Optional[str] = None,
        language_code: Optional[str] = None,
    ) -> bool: ...

    async def get_my_name(
        self,
        *,
        language_code: Optional[str] = None,
    ) -> BotName: ...

    async def set_my_description(
        self,
        *,
        description: Optional[str] = None,
        language_code: Optional[str] = None,
    ) -> bool: ...

    async def get_my_description(
        self,
        *,
        language_code: Optional[str] = None,
    ) -> BotDescription: ...

    async def set_my_short_description(
        self,
        *,
        short_description: Optional[str] = None,
        language_code: Optional[str] = None,
    ) -> bool: ...

    async def get_my_short_description(
        self,
        *,
        language_code: Optional[str] = None,
    ) -> BotShortDescription: ...

    async def set_chat_menu_button(
        self,
        *,
        chat_id: Optional[int] = None,
        menu_button: Optional[MenuButton] = None,
    ) -> bool: ...

    async def get_chat_menu_button(
        self,
        *,
        chat_id: Optional[int] = None,
    ) -> MenuButton: ...

    async def set_my_default_administrator_rights(
        self,
        *,
        rights: Optional[ChatAdministratorRights] = None,
        for_channels: Optional[bool] = None,
    ) -> bool: ...

    async def get_my_default_administrator_rights(
        self,
        *,
        for_channels: Optional[bool] = None,
    ) -> ChatAdministratorRights: ...

    async def edit_message_text(
        self,
        *,
        text: str,
        business_connection_id: Optional[str] = None,
        chat_id: Optional[Union[int, str]] = None,
        message_id: Optional[int] = None,
        inline_message_id: Optional[str] = None,
        parse_mode: Optional[str] = None,
        entities: Optional[list[MessageEntity]] = None,
        link_preview_options: Optional[LinkPreviewOptions] = None,
        reply_markup: Optional[InlineKeyboardMarkup] = None,
    ) -> Union[Message, bool]: ...

    async def edit_message_caption(
        self,
        *,
        business_connection_id: Optional[str] = None,
        chat_id: Optional[Union[int, str]] = None,
        message_id: Optional[int] = None,
        inline_message_id: Optional[str] = None,
        caption: Optional[str] = None,
        parse_mode: Optional[str] = None,
        caption_entities: Optional[list[MessageEntity]] = None,
        show_caption_above_media: Optional[bool] = None,
        reply_markup: Optional[InlineKeyboardMarkup] = None,
    ) -> Union[Message, bool]: ...

    async def edit_message_media(
        self,
        *,
        media: InputMedia,
        business_connection_id: Optional[str] = None,
        chat_id: Optional[Union[int, str]] = None,
        message_id: Optional[int] = None,
        inline_message_id: Optional[str] = None,
        reply_markup: Optional[InlineKeyboardMarkup] = None,
    ) -> Union[Message, bool]: ...

    async def edit_message_live_location(
        self,
        *,
        latitude: float,
        longitude: float,
        business_connection_id: Optional[str] = None,
        chat_id: Optional[Union[int, str]] = None,
        message_id: Optional[int] = None,
        inline_message_id: Optional[str] = None,
        live_period: Optional[int] = None,
        horizontal_accuracy: Optional[float] = None,
        heading: Optional[int] = None,
        proximity_alert_radius: Optional[int] = None,
        reply_markup: Optional[InlineKeyboardMarkup] = None,
    ) -> Union[Message, bool]: ...

    async def stop_message_live_location(
        self,
        *,
        business_connection_id: Optional[str] = None,
        chat_id: Optional[Union[int, str]] = None,
        message_id: Optional[int] = None,
        inline_message_id: Optional[str] = None,
        reply_markup: Optional[InlineKeyboardMarkup] = None,
    ) -> Union[Message, bool]: ...

    async def edit_message_reply_markup(
        self,
        *,
        business_connection_id: Optional[str] = None,
        chat_id: Optional[Union[int, str]] = None,
        message_id: Optional[int] = None,
        inline_message_id: Optional[str] = None,
        reply_markup: Optional[InlineKeyboardMarkup] = None,
    ) -> Union[Message, bool]: ...

    async def stop_poll(
        self,
        *,
        chat_id: Union[int, str],
        message_id: int,
        business_connection_id: Optional[str] = None,
        reply_markup: Optional[InlineKeyboardMarkup] = None,
    ) -> Poll: ...

    async def delete_message(
        self,
        *,
        chat_id: Union[int, str],
        message_id: int,
    ) -> bool: ...

    async def delete_messages(
        self,
        *,
        chat_id: Union[int, str],
        message_ids: list[int],
    ) -> bool: ...

    async def send_sticker(
        self,
        *,
        chat_id: Union[int, str],
        sticker: Union[InputFile, str],
        business_connection_id: Optional[str] = None,
        message_thread_id: Optional[int] = None,
        emoji: Optional[str] = None,
        disable_notification: Optional[bool] = None,
        protect_content: Optional[bool] = None,
        message_effect_id: Optional[str] = None,
        reply_parameters: Optional[ReplyParameters] = None,
        reply_markup: Optional[
            Union[
                InlineKeyboardMarkup,
                ReplyKeyboardMarkup,
                ReplyKeyboardRemove,
                ForceReply,
            ]
        ] = None,
    ) -> Message: ...

    async def get_sticker_set(
        self,
        *,
        name: str,
    ) -> StickerSet: ...

    async def get_custom_emoji_stickers(
        self,
        *,
        custom_emoji_ids: list[str],
    ) -> list[Sticker]: ...

    async def upload_sticker_file(
        self,
        *,
        user_id: int,
        sticker: InputFile,
        sticker_format: str,
    ) -> File: ...

    async def create_new_sticker_set(
        self,
        *,
        user_id: int,
        name: str,
        title: str,
        stickers: list[InputSticker],
        sticker_type: Optional[str] = None,
        needs_repainting: Optional[bool] = None,
    ) -> bool: ...

    async def add_sticker_to_set(
        self,
        *,
        user_id: int,
        name: str,
        sticker: InputSticker,
    ) -> bool: ...

    async def set_sticker_position_in_set(
        self,
        *,
        sticker: str,
        position: int,
    ) -> bool: ...

    async def delete_sticker_from_set(
        self,
        *,
        sticker: str,
    ) -> bool: ...

    async def replace_sticker_in_set(
        self,
        *,
        user_id: int,
        name: str,
        old_sticker: str,
        sticker: InputSticker,
    ) -> bool: ...

    async def set_sticker_emoji_list(
        self,
        *,
        sticker: str,
        emoji_list: list[str],
    ) -> bool: ...

    async def set_sticker_keywords(
        self,
        *,
        sticker: str,
        keywords: Optional[list[str]] = None,
    ) -> bool: ...

    async def set_sticker_mask_position(
        self,
        *,
        sticker: str,
        mask_position: Optional[MaskPosition] = None,
    ) -> bool: ...

    async def set_sticker_set_title(
        self,
        *,
        name: str,
        title: str,
    ) -> bool: ...

    async def set_sticker_set_thumbnail(
        self,
        *,
        name: str,
        user_id: int,
        format: str,
        thumbnail: Optional[Union[InputFile, str]] = None,
    ) -> bool: ...

    async def set_custom_emoji_sticker_set_thumbnail(
        self,
        *,
        name: str,
        custom_emoji_id: Optional[str] = None,
    ) -> bool: ...

    async def delete_sticker_set(
        self,
        *,
        name: str,
    ) -> bool: ...

    async def answer_inline_query(
        self,
        *,
        inline_query_id: str,
        results: list[InlineQueryResult],
        cache_time: Optional[int] = None,
        is_personal: Optional[bool] = None,
        next_offset: Optional[str] = None,
        button: Optional[InlineQueryResultsButton] = None,
    ) -> bool: ...

    async def answer_web_app_query(
        self,
        *,
        web_app_query_id: str,
        result: InlineQueryResult,
    ) -> SentWebAppMessage: ...

    async def send_invoice(
        self,
        *,
        chat_id: Union[int, str],
        title: str,
        description: str,
        payload: str,
        currency: str,
        prices: list[LabeledPrice],
        message_thread_id: Optional[int] = None,
        provider_token: Optional[str] = None,
        max_tip_amount: Optional[int] = None,
        suggested_tip_amounts: Optional[list[int]] = None,
        start_parameter: Optional[str] = None,
        provider_data: Optional[str] = None,
        photo_url: Optional[str] = None,
        photo_size: Optional[int] = None,
        photo_width: Optional[int] = None,
        photo_height: Optional[int] = None,
        need_name: Optional[bool] = None,
        need_phone_number: Optional[bool] = None,
        need_email: Optional[bool] = None,
        need_shipping_address: Optional[bool] = None,
        send_phone_number_to_provider: Optional[bool] = None,
        send_email_to_provider: Optional[bool] = None,
        is_flexible: Optional[bool] = None,
        disable_notification: Optional[bool] = None,
        protect_content: Optional[bool] = None,
        message_effect_id: Optional[str] = None,
        reply_parameters: Optional[ReplyParameters] = None,
        reply_markup: Optional[InlineKeyboardMarkup] = None,
    ) -> Message: ...

    async def create_invoice_link(
        self,
        *,
        title: str,
        description: str,
        payload: str,
        currency: str,
        prices: list[LabeledPrice],
        provider_token: Optional[str] = None,
        max_tip_amount: Optional[int] = None,
        suggested_tip_amounts: Optional[list[int]] = None,
        provider_data: Optional[str] = None,
        photo_url: Optional[str] = None,
        photo_size: Optional[int] = None,
        photo_width: Optional[int] = None,
        photo_height: Optional[int] = None,
        need_name: Optional[bool] = None,
        need_phone_number: Optional[bool] = None,
        need_email: Optional[bool] = None,
        need_shipping_address: Optional[bool] = None,
        send_phone_number_to_provider: Optional[bool] = None,
        send_email_to_provider: Optional[bool] = None,
        is_flexible: Optional[bool] = None,
    ) -> str: ...

    async def answer_shipping_query(
        self,
        *,
        shipping_query_id: str,
        ok: bool,
        shipping_options: Optional[list[ShippingOption]] = None,
        error_message: Optional[str] = None,
    ) -> bool: ...

    async def answer_pre_checkout_query(
        self,
        *,
        pre_checkout_query_id: str,
        ok: bool,
        error_message: Optional[str] = None,
    ) -> bool: ...

    async def get_star_transactions(
        self,
        *,
        offset: Optional[int] = None,
        limit: Optional[int] = None,
    ) -> StarTransactions: ...

    async def refund_star_payment(
        self,
        *,
        user_id: int,
        telegram_payment_charge_id: str,
    ) -> bool: ...

    async def set_passport_data_errors(
        self,
        *,
        user_id: int,
        errors: list[PassportElementError],
    ) -> bool: ...

    async def send_game(
        self,
        *,
        chat_id: int,
        game_short_name: str,
        business_connection_id: Optional[str] = None,
        message_thread_id: Optional[int] = None,
        disable_notification: Optional[bool] = None,
        protect_content: Optional[bool] = None,
        message_effect_id: Optional[str] = None,
        reply_parameters: Optional[ReplyParameters] = None,
        reply_markup: Optional[InlineKeyboardMarkup] = None,
    ) -> Message: ...

    async def set_game_score(
        self,
        *,
        user_id: int,
        score: int,
        force: Optional[bool] = None,
        disable_edit_message: Optional[bool] = None,
        chat_id: Optional[int] = None,
        message_id: Optional[int] = None,
        inline_message_id: Optional[str] = None,
    ) -> Union[Message, bool]: ...

    async def get_game_high_scores(
        self,
        *,
        user_id: int,
        chat_id: Optional[int] = None,
        message_id: Optional[int] = None,
        inline_message_id: Optional[str] = None,
    ) -> list[GameHighScore]: ...
