[project]
name = "alicebot-adapter-apscheduler"
version = "0.9.0"
description = "APScheduler adapter for AliceBot."
authors = [{ name = "st1020", email = "stone_1020@qq.com" }]
license = { text = "MIT" }
readme = "README.md"
keywords = ["bot", "chatbot", "scheduling", "apscheduler"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Framework :: AsyncIO",
    "Framework :: Robot Framework",
    "Framework :: Robot Framework :: Library",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Topic :: Communications :: Chat",
]
requires-python = ">=3.8"
dependencies = ["alicebot==0.9.0", "apscheduler>=3.7,<4.0"]

[project.urls]
Homepage = "https://docs.alicebot.dev/"
Documentation = "https://docs.alicebot.dev/"
Repository = "https://github.com/AliceBotProject/alicebot"
Changelog = "https://docs.alicebot.dev/changelog.html"

[tool.hatch.build]
exclude = ["alicebot/__init__.py", "alicebot/adapter/__init__.py"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
