name: Docs Web Site Deploy

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/tests/**'
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry
        shell: bash
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'
          architecture: 'x64'
          cache: 'poetry'
      - run: poetry install
        shell: bash

      - name: Build API Doc
        run: poetry run sophia-doc alicebot -o docs/api --anchor-extend --ignore-data --overwrite --exclude-module-name --init-file-name README.md
        shell: bash
        env:
          ALICEBOT_DEV: '1'

      - uses: pnpm/action-setup@v2
        with:
          version: ^6.10.0
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'
      - run: pnpm install
        shell: bash

      - name: Build VuePress site
        run: pnpm docs:build

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          repo: st1020/docs.alicebot.dev
          target_branch: master
          build_dir: docs/.vuepress/dist
        env:
          GH_PAT: ${{ secrets.GH_PAGES_TOKEN }}