name: Lint

on:
  push:
    branches:
      - master
    paths:
      - '**.py'
  pull_request:
    paths:
      - '**.py'
  workflow_dispatch:

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pdm-project/setup-pdm@v4
        name: Setup PDM
        with:
          python-version: 3.9
          cache: true
      - name: Install dependencies
        run: pdm install -G dev -G lint

      - run: |
          eval $(pdm venv activate)
          ruff check --output-format=github .
          ruff format --check .

  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pdm-project/setup-pdm@v4
        name: Setup PDM
        with:
          python-version: 3.9
          cache: true
      - name: Install dependencies
        run: pdm install -G dev -G lint

      - run: |
          eval $(pdm venv activate)
          pylint alicebot packages/*

  pyright:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pdm-project/setup-pdm@v4
        name: Setup PDM
        with:
          python-version: 3.9
          cache: true
      - name: Install dependencies
        run: pdm install -G dev -G lint -G typing -G test

      - uses: pnpm/action-setup@v3
        with:
          version: latest
      - uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: pnpm
      - run: pnpm install
        shell: bash

      - run: |
          eval $(pdm venv activate)
          pnpm run pyright

  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pdm-project/setup-pdm@v4
        name: Setup PDM
        with:
          python-version: 3.9
          cache: true
      - name: Install dependencies
        run: pdm install -G dev -G lint -G typing -G test

      - run: |
          eval $(pdm venv activate)
          mypy .
