name: Lint

on:
  push:
    branches:
      - main
    paths:
      - '**.py'
  pull_request:
    paths:
      - '**.py'
  workflow_dispatch:

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: ./.github/actions/setup-python
      - run: uv sync --all-extras --all-packages --group dev --group lint
      - run: |
          uv run ruff check --output-format=github .
          uv run ruff format --check .

  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: ./.github/actions/setup-python
      - run: uv sync --all-extras --all-packages --group dev --group lint
      - run: uv run pylint alicebot packages/*

  pyright:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: ./.github/actions/setup-python
      - run: uv sync --all-extras --all-packages --all-groups
      - run: uv run basedpyright

  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: ./.github/actions/setup-python
      - run: uv sync --all-extras --all-packages --all-groups
      - run: uv run mypy .
