name: Lint Other Files

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.py'
  pull_request:
    paths-ignore:
      - '**.py'
  workflow_dispatch:

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: ./.github/actions/setup-node

      - run: pnpm run prettier

  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: ./.github/actions/setup-node

      - run: pnpm run eslint

  zhlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: ./.github/actions/setup-node

      - run: pnpm run zhlint
