name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry
        shell: bash
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          architecture: "x64"
          cache: "poetry"
      - run: poetry install
        shell: bash

      - name: Remove API Doc
        run: rm -rf docs/api
      - name: Build API Doc
        run: poetry run sophia-doc alicebot -o docs/api --anchor-extend --ignore-data --overwrite --exclude-module-name --init-file-name index.md
        shell: bash
        env:
          ALICEBOT_DEV: "1"
      - name: Commit API Doc
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m "docs: 更新 API 文档"
          git push

      - run: poetry config pypi-token.pypi "$PYPI_TOKEN"
        shell: bash
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}

      - run: poetry publish --build
        shell: bash

      - run: poetry publish --build
        shell: bash
        working-directory: ./packages/alicebot-adapter-apscheduler

      - run: poetry publish --build
        shell: bash
        working-directory: ./packages/alicebot-adapter-cqhttp

      - run: poetry publish --build
        shell: bash
        working-directory: ./packages/alicebot-adapter-onebot

      - run: poetry publish --build
        shell: bash
        working-directory: ./packages/alicebot-adapter-dingtalk

      - run: poetry publish --build
        shell: bash
        working-directory: ./packages/alicebot-adapter-mirai
