name: Release

on:
  workflow_dispatch:

jobs:
  update-api-doc:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - uses: pdm-project/setup-pdm@v4
        name: Setup PDM
        with:
          python-version: 3.9
          cache: true
      - name: Install dependencies
        run: pdm install --no-editable

      - name: Remove API Doc
        run: rm -rf docs/api
      - name: Build API Doc
        run: pdm run sophia-doc alicebot -o docs/api --anchor-extend --ignore-data --overwrite --exclude-module-name --init-file-name index.md
        shell: bash

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: 'docs: 更新 API 文档'
          title: 'docs: 更新 API 文档'
          body: 自动更新 API 文档
          branch: docs/update-api-docs
          base: master

  build:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: pdm-project/setup-pdm@v4
        name: Setup PDM
        with:
          python-version: 3.9
          cache: true
      - name: Install dependencies
        run: pdm install

      - run: pdm publish
        shell: bash

      - run: pdm publish
        shell: bash
        working-directory: ./packages/alicebot-adapter-apscheduler

      - run: pdm publish
        shell: bash
        working-directory: ./packages/alicebot-adapter-cqhttp

      - run: pdm publish
        shell: bash
        working-directory: ./packages/alicebot-adapter-onebot

      - run: pdm publish
        shell: bash
        working-directory: ./packages/alicebot-adapter-dingtalk

      - run: pdm publish
        shell: bash
        working-directory: ./packages/alicebot-adapter-mirai
