name: Release

on:
  workflow_dispatch:

jobs:
  update-api-doc:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: ./.github/actions/setup-python

      - name: Install the project
        run: uv sync --all-extras --all-packages --group dev --group docs
        shell: bash

      - name: Remove API Doc
        run: rm -rf docs/api
      - name: Build API Doc
        run: uv run sophia-doc alicebot -o docs/api --anchor-extend --ignore-data --overwrite --exclude-module-name --init-file-name index.md
        shell: bash
        env:
          ALICEBOT_DEV: '1'

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: 'docs: 更新 API 文档'
          title: 'docs: 更新 API 文档'
          body: 自动更新 API 文档
          branch: docs/update-api-docs
          base: main

  build:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: ./.github/actions/setup-python

      - name: Install the project
        run: uv sync --all-extras --all-packages --group dev
        shell: bash

      - run: uv build -o dist
        shell: bash

      - run: uv build -o dist --package alicebot-adapter-apscheduler
        shell: bash

      - run: uv build -o dist --package alicebot-adapter-cqhttp
        shell: bash

      - run: uv build -o dist --package alicebot-adapter-onebot
        shell: bash

      - run: uv build -o dist --package alicebot-adapter-dingtalk
        shell: bash

      - run: uv build -o dist --package alicebot-adapter-mirai
        shell: bash

      - run: uv build -o dist --package alicebot-adapter-telegram
        shell: bash

      - run: uv publish
        shell: bash
