name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  update-api-doc:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - uses: pdm-project/setup-pdm@v3
        name: Setup PDM
        with:
          python-version: 3.9
          cache: true
      - name: Install dependencies
        run: pdm install

      - name: Remove API Doc
        run: rm -rf docs/api
      - name: Build API Doc
        run: pdm run sophia-doc alicebot -o docs/api --anchor-extend --ignore-data --overwrite --exclude-module-name --init-file-name index.md
        shell: bash
        env:
          ALICEBOT_DEV: "1"
      - name: Commit API Doc
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m "docs: 更新 API 文档"
          git push

  build:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v3

      - uses: pdm-project/setup-pdm@v3
        name: Setup PDM
        with:
          python-version: 3.9
          cache: true
      - name: Install dependencies
        run: pdm install

      - run: pdm publish
        shell: bash

      - run: pdm publish
        shell: bash
        working-directory: ./packages/alicebot-adapter-apscheduler

      - run: pdm publish
        shell: bash
        working-directory: ./packages/alicebot-adapter-cqhttp

      - run: pdm publish
        shell: bash
        working-directory: ./packages/alicebot-adapter-onebot

      - run: pdm publish
        shell: bash
        working-directory: ./packages/alicebot-adapter-dingtalk

      - run: pdm publish
        shell: bash
        working-directory: ./packages/alicebot-adapter-mirai
