name: Spell Check
permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: crate-ci/typos@v1

  autocorrect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: huacnlee/autocorrect-action@main
