name: Spell Check

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: crate-ci/typos@master
